-- Auto-generated from tables.csv and Foreignkey.csv
-- Source folder: Docs/M01-PurchaseRequisition/DB-Schema
-- Generated on: 2026-05-01

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'[dbo].[FA_SLMAS]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[FA_SLMAS]
    (
    [slcode] varchar(8) NOT NULL,
    [slname] varchar(250) NULL,
    [abbr] varchar(5) NULL,
    [add1] varchar(250) NULL,
    [add2] varchar(250) NULL,
    [add3] varchar(50) NULL,
    [city] varchar(50) NULL,
    [pin] varchar(50) NULL,
    [state] varchar(50) NULL,
    [country] varchar(30) NULL,
    [phone1] varchar(30) NULL,
    [phone2] varchar(30) NULL,
    [email] varchar(50) NULL,
    [telegram] varchar(30) NULL,
    [webaddr] varchar(40) NULL,
    [fax] varchar(20) NULL,
    [crlimit] decimal(15,3) NULL,
    [bankadd1] varchar(30) NULL,
    [bankadd2] varchar(30) NULL,
    [carcode] varchar(4) NULL,
    [areacode] varchar(4) NULL,
    [pay_terms] varchar(70) NULL,
    [crddays] decimal(3,0) NULL,
    [tngst] varchar(30) NULL,
    [tngstdt] datetime NULL,
    [cgstdt] datetime NULL,
    [cgst] varchar(30) NULL,
    [ecc] varchar(20) NULL,
    [pan] varchar(20) NULL,
    [trn_debt] char(1) NULL,
    [contper] varchar(30) NULL,
    [contdesg] varchar(30) NULL,
    [contphone] varchar(30) NULL,
    [prtytyp] varchar(2) NULL,
    [BRCODE] varchar(7) NULL,
    [tax_code] varchar(3) NULL,
    [insper] decimal(5,2) NULL,
    [DISC_PER] decimal(5,2) NULL,
    [CDISC_PER] decimal(5,2) NULL,
    [passwd] varchar(10) NULL,
    [stcode] numeric(1,0) NULL,
    [PAYMODE] tinyint NULL,
    [PARTY_TYPE] varchar(2) NULL,
    [RANGE] varchar(50) NULL,
    [DIVISION] varchar(50) NULL,
    [AGENT_CODE] varchar(6) NULL,
    [CARRIER_CODE] varchar(4) NULL,
    [RC_NO] varchar(15) NULL,
    [COLLECTORATE] varchar(25) NULL,
    [AC_SL] varchar(6) NULL,
    [INSPECT] char(1) NULL,
    [APPROVE] char(1) NULL,
    [GROUPCODE] varchar(2) NULL,
    [state_code] varchar(3) NULL,
    [TINNO] varchar(50) NULL,
    [TINDT] varchar(15) NULL,
    [odper] decimal(5,2) NULL,
    [self] char(1) NULL,
    [COMM_TYPE] char(1) NULL,
    [COMM_PER] numeric(5,3) NULL,
    [org_type] varchar(3) NULL,
    [OFF_ADD1] varchar(70) NULL,
    [OFF_ADD2] varchar(70) NULL,
    [OFF_ADD3] varchar(70) NULL,
    [OFF_CITY] varchar(70) NULL,
    [OFF_PIN] varchar(12) NULL,
    [OFF_STATE] varchar(25) NULL,
    [OFF_COUNTRY] varchar(30) NULL,
    [OFF_PHONE1] varchar(40) NULL,
    [OFF_PHONE2] varchar(30) NULL,
    [OFF_EMAIL] varchar(40) NULL,
    [OFF_TELEGRAM] varchar(30) NULL,
    [OFF_WEBSITE] varchar(40) NULL,
    [OFF_FAX] varchar(40) NULL,
    [OFF_CONTPER] varchar(30) NULL,
    [OFF_contdesg] varchar(30) NULL,
    [OFF_CONTPHONE] varchar(30) NULL,
    [OFF_SSINO] varchar(30) NULL,
    [OFF_MICRONO] varchar(30) NULL,
    [default_Add] varchar(100) NULL,
    [grp] varchar(1) NULL,
    [COURIERTHROUGH] nvarchar(100) NULL,
    [BANKACNO] varchar(50) NULL,
    [IFSCCODE] varchar(50) NULL,
    [USERID] varchar(15) NULL,
    [CustGrp] varchar(8) NULL,
    [CRLimitflg] varchar(2) NULL,
    [ptype] varchar(2) NULL,
    [OLDSLCODE] varchar(8) NULL,
    [email2] varchar(50) NULL,
    [ACTYPE] varchar(10) NULL,
    [user_name] varchar(35) NULL,
    [password] varchar(10) NULL,
    [UserType] char(1) NULL,
    [isactive] varchar(1) NULL,
    [gstinno] varchar(15) NULL,
    [gststatecode] varchar(2) NULL,
    [supptype] varchar(1) NULL,
    [CRDDAYS2] decimal(3,0) NULL,
    [SubRegionCode] varchar(5) NULL,
    [rate_type] varchar(20) NULL,
    [Region] varchar(5) NULL,
    [zonecode] varchar(2) NULL,
    [mod_date] datetime NULL,
    [mod_user] varchar(20) NULL,
    [ipaddr] varchar(20) NULL,
    [hostname] varchar(20) NULL,
    [mod_form] varchar(20) NULL,
    [mod_username] varchar(20) NULL,
    [scanfilename] varchar(200) NULL,
    [active] char(1) NULL,
    [TDS_TCS_Flg] char(1) NULL,
    [CR_DaysLock] tinyint NULL,
    [PolicyNo] varchar(30) NULL,
    [PeriodFDt] datetime NULL,
    [PeriodTDt] datetime NULL,
    [TDS_TCS_Cal_Flg] char(1) NULL,
    [TypeofEnterprise] varchar(2) NULL,
    [MSME_GroupType] varchar(2) NULL,
    [MSME_Group] varchar(2) NULL,
    [UAM] varchar(13) NULL,
    [GSTORPAN_File] varchar(40) NULL,
    [MSME_CERTIFICATE_File] varchar(40) NULL,
    [branch_name] varchar(25) NULL,
    [Cheque_Favour] varchar(55) NULL,
    [Internal_EMailID] varchar(20) NULL,
    [TANNO] varchar(10) NULL,
    [Short_Name] varchar(16) NULL,
    [MailSend] char(1) NULL,
    [isautomailflg] char(2) NULL,
    [CIN] varchar(21) NULL,
    [CSM_Slcode] varchar(10) NULL,
    [CSM_SlName] varchar(250) NULL,
    [IsIntUnitTrans] tinyint NULL,
    [IntUnitGL] varchar(6) NULL,
    CONSTRAINT [PK_FA_SLMAS] PRIMARY KEY ([slcode])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_BGRP]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_BGRP]
    (
    [BGRPCODE] varchar(4) NULL,
    [BGRPNAME] varchar(100) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_CAT]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_CAT]
    (
    [CATCODE] varchar(1) NOT NULL,
    [CATDESC] varchar(25) NULL,
    [Active] varchar(5) NULL,
    CONSTRAINT [PK_IN_CAT] PRIMARY KEY ([CATCODE])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_CC]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_CC]
    (
    [CCCODE] varchar(5) NOT NULL,
    [CCNAME] varchar(25) NOT NULL,
    [DPGRCD] numeric(2,0) NULL,
    [CGCODE] numeric(2,0) NULL,
    [divcode] varchar(2) NOT NULL,
    [Active] varchar(5) NULL,
    CONSTRAINT [PK_IN_CC] PRIMARY KEY ([CCCODE], [divcode])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_DEP]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_DEP]
    (
    [DEPCODE] varchar(3) NOT NULL,
    [DEPNAME] varchar(30) NOT NULL,
    [SEQNO] numeric(2,0) NULL,
    [CCCODE] varchar(5) NULL,
    [divcode] varchar(2) NOT NULL,
    [unitCode] varchar(2) NULL,
    [dep_grp] varchar(2) NULL,
    [substore] char(1) NULL,
    [active] char(1) NULL,
    [dgroup] varchar(15) NULL,
    [dgrpname] varchar(100) NULL,
    CONSTRAINT [PK_IN_DEP] PRIMARY KEY ([DEPCODE], [divcode])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_GRP]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_GRP]
    (
    [GRPCODE] varchar(3) NOT NULL,
    [GRPNAME] varchar(30) NOT NULL,
    [GLCODE] varchar(6) NULL,
    [MACGRP] char(1) NULL,
    [comm_code] varchar(15) NULL,
    [Consu_DrGlcode] varchar(7) NULL,
    [Consu_CrGlcode] varchar(7) NULL,
    [Active] varchar(5) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_ITEM]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_ITEM]
    (
    [ITEMCODE] varchar(10) NOT NULL,
    [ITEMNAME] varchar(70) NOT NULL,
    [ITEMSPEC1] varchar(150) NULL,
    [ITEMSPEC2] varchar(150) NULL,
    [ITEMSPEC3] varchar(150) NULL,
    [UOM] varchar(3) NOT NULL,
    [CUOM] varchar(3) NOT NULL,
    [UOMQTY] numeric(12,3) NULL,
    [CUOMQTY] numeric(12,3) NULL,
    [MATYPE] char(1) NULL,
    [AUTOMRP] char(1) NULL,
    [CATCODE] varchar(1) NULL,
    [CATFLG] tinyint NULL,
    [CATLNO] varchar(25) NULL,
    [MACNO] varchar(5) NULL,
    [MAXLEVEL] numeric(12,3) NULL,
    [MINLEVEL] decimal(12,3) NULL,
    [RORDLEVEL] numeric(12,3) NULL,
    [RORDQTY] decimal(12,3) NULL,
    [RATE] numeric(15,5) NULL,
    [CURSTK] decimal(20,3) NULL,
    [PHYSTK] decimal(12,3) NULL,
    [LRECPTDT] datetime NULL,
    [LISSUEDT] datetime NULL,
    [ABCFLG] char(1) NULL,
    [FSNFLG] char(1) NULL,
    [LOCATION] varchar(15) NULL,
    [HIGHSTK] numeric(11,3) NULL,
    [HIGHDATE] datetime NULL,
    [LOWSTK] numeric(11,3) NULL,
    [LOWDATE] datetime NULL,
    [UDELYTOL] numeric(12,3) NULL,
    [ODELFLG] char(1) NULL,
    [ODELTOL] numeric(12,3) NULL,
    [LEVYTAX] numeric(12,2) NULL,
    [FREITINS] numeric(12,2) NULL,
    [qcstock] numeric(12,3) NULL,
    [rejstk] numeric(12,3) NULL,
    [INDENTREQ] char(1) NULL,
    [VALUED] char(1) NULL,
    [DEADSTOCK] char(1) NULL,
    [SUBSTOREITEM] char(1) NULL,
    [LIFETYPE] char(1) NULL,
    [LIFESPAN] numeric(3,0) NULL,
    [GODCODE] varchar(2) NULL,
    [ITEMIMAGE] image NULL,
    [dutycat] char(1) NULL,
    [frequency] char(1) NULL,
    [dutydocno] varchar(8) NULL,
    [PREORDNO] numeric(6,0) NULL,
    [PREPRICE] numeric(15,2) NULL,
    [MON3LORDNO] numeric(6,0) NULL,
    [MON3LPRICE] numeric(15,2) NULL,
    [MON12LORDNO] numeric(6,0) NULL,
    [MON12LPRICE] numeric(15,2) NULL,
    [DRAWNO] varchar(25) NULL,
    [SELFLIFE] char(1) NULL,
    [MAKPARTNO] varchar(20) NULL,
    [PARTNO] varchar(20) NULL,
    [APMFlag] varchar(1) NULL,
    [Lncode] varchar(12) NULL,
    [ImagePath] varchar(200) NULL,
    [COM_CODE] varchar(20) NULL,
    [prispec] varchar(300) NULL,
    [OpQty] numeric(15,3) NULL,
    [OpVal] numeric(15,2) NULL,
    [Critical_Item] char(10) NULL,
    [Insp_Type_Code] varchar(6) NULL,
    [sgrpcode] varchar(3) NULL,
    [old_itemcode] varchar(7) NULL,
    [TEMP_DIVCODE] varchar(2) NULL,
    [flag] char(1) NULL,
    [essflag] char(1) NULL,
    [scrap_Item] varchar(1) NULL,
    [suom] varchar(3) NULL,
    [iWEIGHT] decimal(12,3) NULL,
    [hsncode] varchar(8) NULL,
    [cgst_per] numeric(6,2) NULL,
    [sgst_per] numeric(6,2) NULL,
    [igst_per] numeric(6,2) NULL,
    [gsttaxcode] varchar(3) NULL,
    [IsItemActive] tinyint NULL,
    [MACHINEMAKE_ID] varchar(15) NULL,
    [MODEL] varchar(25) NULL,
    [MACHINEMAKEID] varchar(15) NULL,
    [MODELID] varchar(25) NULL,
    CONSTRAINT [PK_IN_ITEM] PRIMARY KEY ([ITEMCODE])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_MAC]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_MAC]
    (
    [MACNO] varchar(5) NOT NULL,
    [MACDES] varchar(30) NOT NULL,
    [MAKE] varchar(25) NULL,
    CONSTRAINT [PK_IN_MAC] PRIMARY KEY ([MACNO])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_PARA]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_PARA]
    (
    [APER] decimal(2,0) NULL,
    [BPER] decimal(2,0) NULL,
    [FTIMES] decimal(2,0) NULL,
    [STIMES] decimal(2,0) NULL,
    [XPER] decimal(2,0) NULL,
    [YPER] decimal(2,0) NULL,
    [GTFRITC] numeric(2,0) NULL,
    [GTFROTC] numeric(2,0) NULL,
    [FAINSTAL] char(1) NOT NULL,
    [FATFR] char(1) NOT NULL,
    [FATC] numeric(2,0) NULL,
    [rg23a] varchar(2) NULL,
    [rg23c] varchar(2) NULL,
    [BUDREQ] char(1) NULL,
    [FaDbtc] numeric(3,0) NULL,
    [PoRdays] numeric(5,0) NULL,
    [RecTcFrom] numeric(5,0) NULL,
    [RecTcTo] numeric(5,0) NULL,
    [MIBRTC] numeric(5,0) NULL,
    [MIBITC] numeric(5,0) NULL,
    [IssTcFrom] numeric(5,0) NULL,
    [IssTcTo] numeric(5,0) NULL,
    [RecRetTcFrom] numeric(5,0) NULL,
    [RecRetTcTo] numeric(5,0) NULL,
    [IssRetTcFrom] numeric(5,0) NULL,
    [IssRetTcTo] numeric(5,0) NULL,
    [UnitTransInTcFrom] numeric(5,0) NULL,
    [UnitTransInTcTo] numeric(5,0) NULL,
    [UnitTransOutTcFrom] numeric(5,0) NULL,
    [UnitTransOutTcTo] numeric(5,0) NULL,
    [AdjPlusTcFrom] numeric(5,0) NULL,
    [AdjPlusTcTo] numeric(5,0) NULL,
    [AdjMinTcFrom] numeric(5,0) NULL,
    [AdjMinTcTo] numeric(5,0) NULL,
    [UsedItemTransTcFrom] numeric(5,0) NULL,
    [UsedItemTransTcTo] numeric(5,0) NULL,
    [MiscTcFrom] numeric(5,0) NULL,
    [MiscTcTo] numeric(5,0) NULL,
    [vatgl] varchar(6) NULL,
    [vatgl2] varchar(6) NULL,
    [vatflg] char(1) NULL,
    [MIBENABLE] varchar(1) NULL,
    [Cenvatflg] char(1) NULL,
    [CenvatGL] varchar(6) NULL,
    [Cenvatgl2] varchar(6) NULL,
    [PackItmGrp] varchar(5) NULL,
    [MOVELINKFLG] char(1) NULL,
    [ASSETCAT] varchar(1) NULL,
    [servicebilltc] numeric(5,0) NULL,
    [GRNWITHIND] char(1) NULL,
    [CashPurCode] varchar(5) NULL,
    [Bill_Issue_Flg] char(1) NULL,
    [Job_Print_Flg] char(1) NULL,
    [Iss_Print_Flg] char(1) NULL,
    [Inspection_Flg] char(1) NULL,
    [bill_additionaltax] char(2) NULL,
    [Div_ItemStock] char(1) NULL,
    [BillEntryApp_Flg] char(1) NULL,
    [iss_req_cl_days] numeric(3,0) NULL,
    [Tr_FromDate] datetime NULL,
    [Tr_toDate] datetime NULL,
    [TransOUTgl] varchar(7) NULL,
    [TransINgl] varchar(7) NULL,
    [TransTC] varchar(7) NULL,
    [GRNAutoSMS] char(1) NULL,
    [GRNAutoSMSflg] char(1) NULL,
    [job_cl_days] numeric(5,0) NULL,
    [outpassNoGen] char(1) NULL,
    [EveSnacksRate] numeric(7,2) NULL,
    [EveSnacksCat] varchar(20) NULL,
    [EveSnacksType] varchar(20) NULL,
    [DEPTCODE] varchar(20) NULL,
    [Dieselcode] varchar(7) NULL,
    [article] varchar(2) NULL,
    [FIFO] varchar(1) NULL,
    [wpoamt] decimal(15,2) NULL,
    [starch] varchar(3) NULL,
    [chemicals] varchar(3) NULL,
    [Dyes] varchar(3) NULL,
    [Fuel] varchar(3) NULL,
    [RCMDBGL] varchar(6) NULL,
    [RCMCGSTGL] varchar(6) NULL,
    [RCMSGSTGL] varchar(6) NULL,
    [RCMIGSTGL] varchar(6) NULL,
    [RCMCGSTGL_DBT] varchar(6) NULL,
    [RCMSGSTGL_DBT] varchar(6) NULL,
    [RCMIGSTGL_DBT] varchar(6) NULL,
    [PurTypeFlg] int NULL,
    [Issuereq] varchar(2) NULL,
    [StkDRGL] varchar(10) NULL,
    [StkCRGL] varchar(10) NULL,
    [serpo_billlink] varchar(10) NULL,
    [billvalue] varchar(10) NULL,
    [tcsflg] varchar(10) NULL,
    [tcs_per] numeric(15,4) NULL,
    [webreportlink] varchar(100) NULL,
    [penpodetails] varchar(20) NULL,
    [serviceporate] varchar(20) NULL,
    [tcs_value] decimal(9,0) NULL,
    [tcstax] varchar(25) NULL,
    [indwithpo] varchar(5) NULL,
    [tdsflg] varchar(5) NULL,
    [tds_perpan] numeric(15,3) NULL,
    [tds_wopan] numeric(15,3) NULL,
    [tds_value] numeric(15,2) NULL,
    [tdstype] varchar(25) NULL,
    [MsAccs_Tran_Flg] varchar(50) NULL,
    [MsAcs_Path] varchar(50) NULL,
    [serviceweb] varchar(10) NULL,
    [Tds_Rndnextrs] tinyint NULL,
    [DateDivision] varchar(5) NULL,
    [gatedivision] varchar(5) NULL,
    [importtds] varchar(5) NULL,
    [outpassapproval] varchar(25) NULL,
    [backdate] varchar(5) NULL,
    [Issue_After_Bill] varchar(10) NULL,
    [PartialTdscal] varchar(5) NULL,
    [advancetdscalc] varchar(5) NULL,
    [Lastyrmaterialreturn] varchar(5) NULL,
    [scrapreturn] varchar(5) NULL,
    [ScrapPwd] varchar(50) NULL,
    [freightTC] varchar(5) NULL,
    [Lastyrreceiptreturn] varchar(5) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[in_repfoot]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[in_repfoot]
    (
    [footcode] varchar(3) NOT NULL,
    [footdesc] varchar(50) NULL,
    [divcode] varchar(2) NOT NULL,
    [active] varchar(5) NULL,
    CONSTRAINT [PK_in_repfoot] PRIMARY KEY ([footcode], [divcode])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_SCC]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_SCC]
    (
    [SCCCODE] numeric(6,0) NOT NULL,
    [SCCNAME] varchar(40) NULL,
    [DEPCODE] varchar(5) NOT NULL,
    [mastid] int NOT NULL,
    [Divcode] varchar(2) NOT NULL,
    [CC_Code] varchar(5) NULL,
    [Consu_DrGlcode] varchar(7) NULL,
    [Consu_CrGlcode] varchar(7) NULL,
    [UserId] varchar(15) NULL,
    [CRDate] varchar(15) NULL,
    [Active] varchar(5) NULL,
    CONSTRAINT [PK_IN_SCC] PRIMARY KEY ([SCCCODE], [Divcode])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_TRNHEAD]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_TRNHEAD]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [TC] numeric(2,0) NOT NULL,
    [DOCNO] numeric(6,0) NOT NULL,
    [DOCDT] datetime NOT NULL,
    [DCNO] varchar(20) NULL,
    [DCDT] datetime NULL,
    [SLCODE] varchar(7) NULL,
    [DEPCODE] varchar(3) NULL,
    [REFNO] varchar(20) NULL,
    [REFTC] numeric(2,0) NULL,
    [REFDT] datetime NULL,
    [BATCHNO] varchar(15) NULL,
    [MODEOFDEL] varchar(25) NULL,
    [TRN_DEBT] char(1) NULL,
    [CFORM] char(1) NULL,
    [CFORMREF] varchar(25) NULL,
    [FORM37REF] varchar(25) NULL,
    [FORMH] char(1) NULL,
    [FORMHREF] varchar(25) NULL,
    [PAY_DUEDT] datetime NULL,
    [FORM17] char(1) NULL,
    [FORM17REF] varchar(25) NULL,
    [opflg] char(1) NOT NULL,
    [APPROVED1] char(1) NULL,
    [APPROVED2] char(1) NULL,
    [IRNO] numeric(6,0) NULL,
    [REMARKS] varchar(40) NULL,
    [TOTVALUE] numeric(18,2) NULL,
    [ROFF] numeric(15,2) NULL,
    [BILLNO] varchar(30) NULL,
    [BILLDT] datetime NULL,
    [IWGPNO] varchar(15) NULL,
    [DBNO] varchar(5) NULL,
    [DBDT] datetime NULL,
    [DBTC] varchar(3) NULL,
    [DBAMT] numeric(10,2) NULL,
    [WEIGHBILLAMT] numeric(10,2) NULL,
    [Sqno] numeric(5,0) NULL,
    [TrDivcode] varchar(2) NULL,
    [OutDocNo] numeric(5,0) NULL,
    [MIBDESFLG] char(1) NULL,
    [LRREFNO] varchar(7) NULL,
    [LRDT] datetime NULL,
    [RECFLG] char(1) NULL,
    [TYear] numeric(5,0) NOT NULL,
    [Tran_Type] varchar(1) NULL,
    [po_type] varchar(3) NULL,
    [Vehicleno] varchar(15) NULL,
    [CPerson] varchar(20) NULL,
    [Stime] datetime NULL,
    [DISPER] numeric(5,2) NULL,
    [PCKPER] numeric(5,2) NULL,
    [CESSPER] numeric(5,2) NULL,
    [BXDPER] numeric(5,2) NULL,
    [AEDPER] numeric(5,2) NULL,
    [EDUCESSPER] numeric(5,2) NULL,
    [HSCESSPER] numeric(5,2) NULL,
    [TAXCODE] varchar(3) NULL,
    [TAXPER] numeric(5,2) NULL,
    [SURPER] numeric(5,2) NULL,
    [FREIGHT] numeric(15,2) NULL,
    [INSPER] numeric(5,2) NULL,
    [BEDPER] numeric(5,2) NULL,
    [SStime] varchar(12) NULL,
    [alert_raised] char(1) NULL,
    [IWGPDT] datetime NULL,
    [Insp_Date] datetime NULL,
    [FORM_TYPE] varchar(5) NULL,
    [TBillDt] datetime NULL,
    [TBillNo] varchar(30) NULL,
    [ST_Docno] numeric(5,0) NULL,
    [ST_Docdt] datetime NULL,
    [BillFlg] char(1) NULL,
    [TAXAMT] numeric(12,2) NULL,
    [DISAMT] numeric(15,2) NULL,
    [PACK1AMT] numeric(15,2) NULL,
    [CESSAMT] numeric(15,2) NULL,
    [BEDAMT] numeric(15,2) NULL,
    [AEDAMT] numeric(15,2) NULL,
    [EDUCESSAMT] numeric(15,2) NULL,
    [HscessAmt] numeric(15,2) NULL,
    [SCAMT] numeric(15,2) NULL,
    [ADSCAMT] numeric(15,2) NULL,
    [INS1AMT] numeric(15,2) NULL,
    [COTHCHGS] numeric(15,2) NULL,
    [hgodcode] varchar(3) NULL,
    [cust_gststcode] varchar(2) NULL,
    [gstinno] varchar(15) NULL,
    [createdby] varchar(15) NULL,
    [createddt] datetime NULL,
    [modifiedby] varchar(25) NULL,
    [modifydt] datetime NULL,
    [inspby] varchar(25) NULL,
    [inspdate] datetime NULL,
    [htcs_amt] numeric(15,2) NULL,
    [caporder] varchar(10) NULL,
    [FrtValue] numeric(15,2) NULL,
    [staform] varchar(5) NULL,
    [igwpdate] datetime NULL,
    [iwgpdate] datetime NULL,
    [dcgst] decimal(9,3) NULL,
    [dsgst] decimal(9,3) NULL,
    [digst] decimal(9,3) NULL,
    [IGPWNO] varchar(15) NULL,
    [SampleFlag] varchar(2) NULL,
    [RHdebit_roff] numeric(15,2) NULL,
    [RHdebit_Assvalue] numeric(15,2) NULL,
    [RHdebit_cgstamt] numeric(15,2) NULL,
    [RHdebit_sgstamt] numeric(15,2) NULL,
    [RHdebit_igstamt] numeric(15,2) NULL,
    [TransID] varchar(10) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[IN_TRNTAIL]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[IN_TRNTAIL]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [TC] numeric(2,0) NOT NULL,
    [DOCNO] numeric(6,0) NOT NULL,
    [DOCDT] datetime NOT NULL,
    [DOCSNO] decimal(5,0) NOT NULL,
    [ITEMCODE] varchar(10) NOT NULL,
    [QCRECDQTY] decimal(12,3) NULL,
    [QUANTITY] decimal(12,3) NULL,
    [RATE] decimal(15,5) NULL,
    [VALUE] decimal(15,2) NULL,
    [MACNO] varchar(5) NULL,
    [CCCODE] numeric(6,0) NULL,
    [REMARK1] varchar(20) NULL,
    [pordno] decimal(6,0) NULL,
    [porddt] datetime NULL,
    [pogrp] varchar(2) NULL,
    [refdocno] decimal(6,0) NULL,
    [refdt] datetime NULL,
    [reftc] decimal(2,0) NULL,
    [refdocsno] decimal(6,0) NULL,
    [refqty] decimal(12,3) NULL,
    [category] char(1) NULL,
    [BATCHNO] varchar(15) NULL,
    [QCPERSON] varchar(6) NULL,
    [REJQTY] decimal(12,3) NULL,
    [REPLQTY] decimal(12,3) NULL,
    [abrate] decimal(12,2) NULL,
    [GODCODE] varchar(2) NOT NULL,
    [PJTC] decimal(3,0) NULL,
    [PJNO] decimal(6,0) NULL,
    [PJDT] datetime NULL,
    [PAYQTY] decimal(12,3) NULL,
    [returnable] char(1) NULL,
    [NOOFISS] decimal(4,0) NULL,
    [RECNO] decimal(6,0) NULL,
    [ADJQTY] decimal(12,3) NULL,
    [BALQTY] decimal(12,3) NULL,
    [ISSQTY] decimal(12,3) NULL,
    [RECDT] datetime NULL,
    [TISS] decimal(12,3) NULL,
    [opflg] char(1) NOT NULL,
    [irno] decimal(6,0) NULL,
    [irdate] datetime NULL,
    [remarks] varchar(100) NULL,
    [PARTNO] varchar(12) NULL,
    [DIS_PER] numeric(5,2) NULL,
    [DIS_AMT] numeric(15,2) NULL,
    [PACK1_PER] numeric(5,2) NULL,
    [PACK1_AMT] numeric(15,2) NULL,
    [INS1_PER] numeric(5,2) NULL,
    [INS1_AMT] numeric(15,2) NULL,
    [BED_PER] numeric(5,2) NULL,
    [BED_AMT] numeric(15,2) NULL,
    [AED_PER] numeric(5,2) NULL,
    [AED_AMT] numeric(15,2) NULL,
    [EDUCESS_PER] numeric(5,2) NULL,
    [EDUCESS_AMT] numeric(15,2) NULL,
    [FRT1_PER] numeric(5,2) NULL,
    [FRT1_AMT] numeric(15,2) NULL,
    [TAX_PER] numeric(5,2) NULL,
    [TAX_AMT] numeric(15,2) NULL,
    [SC_PER] numeric(5,2) NULL,
    [SC_AMT] numeric(15,2) NULL,
    [ADSC_PER] numeric(5,2) NULL,
    [ADSC_AMT] numeric(15,2) NULL,
    [FRT2_PER] numeric(5,2) NULL,
    [FRT2_AMT] numeric(15,2) NULL,
    [PACK2_PER] numeric(5,2) NULL,
    [PACK2_AMT] numeric(15,2) NULL,
    [INS2_PER] numeric(5,2) NULL,
    [INS2_AMT] numeric(15,2) NULL,
    [OTHCHGS] numeric(15,2) NULL,
    [TOTVALUE] numeric(15,2) NULL,
    [BILLNO] varchar(30) NULL,
    [BILLDT] datetime NULL,
    [CESS_PER] numeric(5,2) NULL,
    [CESS_AMT] numeric(15,2) NULL,
    [ROFF] numeric(9,2) NULL,
    [Sqno] numeric(5,0) NULL,
    [PACK_FLG] varchar(1) NULL,
    [FRT_FLG] varchar(1) NULL,
    [EXC_FLG] varchar(1) NULL,
    [Ins_Flg] varchar(1) NULL,
    [PORDSNO] numeric(5,0) NULL,
    [VALUEWOWEIGH] numeric(15,2) NULL,
    [Return_Qty] numeric(15,3) NULL,
    [MIBNO] numeric(5,0) NULL,
    [MIBDATE] datetime NULL,
    [MIBDESFLG] char(1) NULL,
    [RECFLG] char(1) NULL,
    [TYear] numeric(5,0) NOT NULL,
    [RecTc] numeric(5,0) NULL,
    [rejcode] varchar(3) NULL,
    [POQTY] numeric(6,0) NULL,
    [ValueWithTax] decimal(15,2) NULL,
    [itctax] decimal(15,2) NULL,
    [itcsc] decimal(15,2) NULL,
    [TAX_CODE] varchar(3) NULL,
    [Hscess_per] numeric(5,2) NULL,
    [Hscess_Amt] numeric(15,2) NULL,
    [Scope] varchar(2) NULL,
    [IndentNo] numeric(6,0) NULL,
    [IndentDt] datetime NULL,
    [IndentUnit] varchar(2) NULL,
    [IndentSno] numeric(6,0) NULL,
    [VCat] varchar(2) NULL,
    [Cess_flg] varchar(1) NULL,
    [disflg] char(1) NULL,
    [balvalue] numeric(15,2) NULL,
    [recdocsno] numeric(5,0) NULL,
    [DEPCODE] varchar(3) NULL,
    [debitdiscamt] numeric(15,3) NULL,
    [TEMP_QUANTITY] numeric(15,3) NULL,
    [TEMP_value] numeric(15,2) NULL,
    [issRet_flg] varchar(1) NULL,
    [posno] numeric(5,0) NULL,
    [DebitAmt] numeric(12,2) NULL,
    [ATax_Code] varchar(3) NULL,
    [ATax_per] numeric(5,2) NULL,
    [ATax_Amt] numeric(15,2) NULL,
    [strflg] char(1) NULL,
    [gTaxEdit_Flg] char(1) NULL,
    [CRFLG] char(1) NULL,
    [SampleFlg] char(1) NULL,
    [CapGoodsFlg] varchar(1) NULL,
    [FOCFlg] varchar(2) NULL,
    [SizeQty] numeric(15,3) NULL,
    [taxadj_amt] numeric(15,2) NULL,
    [TStkQty] decimal(12,3) NULL,
    [TStkRate] decimal(15,5) NULL,
    [TStk_Value] decimal(15,2) NULL,
    [IssueValue] decimal(15,2) NULL,
    [crdate] datetime NULL,
    [hsncode] varchar(8) NULL,
    [cgstper] numeric(5,2) NULL,
    [cgstamt] numeric(10,2) NULL,
    [sgstper] numeric(5,2) NULL,
    [sgstamt] numeric(10,2) NULL,
    [igstper] numeric(5,2) NULL,
    [igstamt] numeric(10,2) NULL,
    [cgst_tax_code] varchar(10) NULL,
    [sgst_tax_code] varchar(10) NULL,
    [igst_tax_code] varchar(10) NULL,
    [taxadjamt] numeric(15,3) NULL,
    [iaWEIGHT] numeric(15,3) NULL,
    [deletereason] varchar(25) NULL,
    [tcs_per] numeric(15,4) NULL,
    [tcs_amt] numeric(15,2) NULL,
    [scrapretqty] numeric(15,2) NULL,
    [scrapretflg] varchar(5) NULL,
    [reccategory] varchar(5) NULL,
    [issuereason] varchar(70) NULL,
    [issueaction] varchar(70) NULL,
    [Rdebit_roff] numeric(15,2) NULL,
    [Rdebit_Assvalue] numeric(15,2) NULL,
    [Rdebit_cgstamt] numeric(15,2) NULL,
    [Rdebit_sgstamt] numeric(15,2) NULL,
    [Rdebit_igstamt] numeric(15,2) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[mm_macmas]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[mm_macmas]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [DEPCODE] varchar(3) NOT NULL,
    [MAC_NO] varchar(5) NOT NULL,
    [DESCRIPTION] varchar(30) NULL,
    [MODEL] varchar(20) NULL,
    [MAC_CODE] varchar(5) NOT NULL,
    [ADEPCODE] varchar(2) NULL,
    [CATCODE] varchar(2) NULL,
    [SUBCATCODE] varchar(2) NULL,
    [ASSETSNO] numeric(3,0) NULL,
    [TOTCOST] numeric(12,2) NULL,
    [ST_INS_FLG] char(1) NOT NULL,
    [ST_DUE_DT] datetime NULL,
    [MAC_HRRATE] numeric(8,2) NULL,
    [INSTALL_DT] datetime NULL,
    [mac_refno] varchar(20) NULL,
    [MACFLAG] char(1) NOT NULL,
    [temp] varchar(5) NULL,
    [imagepath] varchar(200) NULL,
    [MacLength] numeric(8,3) NULL,
    [macWidth] numeric(8,3) NULL,
    [MacAirReq] numeric(7,2) NULL,
    [MacMotorKw] numeric(7,2) NULL,
    [Mac_ManuFactDate] varchar(6) NULL,
    [PartyCode] varchar(7) NULL,
    [mac_modifyDetails] varchar(100) NULL,
    [MacMake] varchar(25) NULL,
    [MacSerialNo] varchar(20) NULL,
    [UnitCode] varchar(2) NOT NULL,
    [Cable_Specification] varchar(20) NULL,
    [ElecroValves] varchar(100) NULL,
    [salesflag] char(2) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_DOC_PARA]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_DOC_PARA]
    (
    [TC] varchar(20) NOT NULL,
    [STDOCNO] decimal(6,0) NULL,
    CONSTRAINT [PK_PO_DOC_PARA] PRIMARY KEY ([TC])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_ENQL]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_ENQL]
    (
    [divcode] varchar(2) NOT NULL,
    [enqno] numeric(6,0) NOT NULL,
    [enqdt] datetime NOT NULL,
    [enqsno] numeric(5,0) NOT NULL,
    [prno] numeric(6,0) NULL,
    [prdate] datetime NULL,
    [prsno] numeric(5,0) NULL,
    [itemcode] varchar(10) NULL,
    [qtyreqd] numeric(12,3) NULL,
    [reqddt] datetime NULL,
    [estatus] char(1) NULL,
    [MAKPARTNO] varchar(20) NULL,
    [remarks] varchar(20) NULL,
    CONSTRAINT [PK_PO_ENQL] PRIMARY KEY ([divcode], [enqno], [enqdt], [enqsno])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_ORDH]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_ORDH]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [PORDNO] numeric(6,0) NOT NULL,
    [PORDDT] datetime NOT NULL,
    [POGRP] varchar(2) NOT NULL,
    [SLCODE] varchar(7) NULL,
    [QUOTNO] varchar(15) NULL,
    [QUOTDT] datetime NULL,
    [ORDVAL] numeric(15,2) NULL,
    [ADV_PER] numeric(6,2) NULL,
    [ADV_AMT] numeric(15,2) NULL,
    [FRTFLG] char(1) NULL,
    [BANK_CODE] varchar(6) NULL,
    [PAYMENT] varchar(1) NULL,
    [FREIGHT] numeric(15,2) NULL,
    [DISPER] numeric(5,2) NULL,
    [TAXPER] numeric(5,2) NULL,
    [EXDPER] numeric(5,2) NULL,
    [SEDPER] numeric(5,2) NULL,
    [PCKPER] numeric(5,2) NULL,
    [INSPER] numeric(5,2) NULL,
    [SURPER] numeric(5,2) NULL,
    [MODVAT] numeric(5,2) NULL,
    [PAYTERMS] varchar(100) NULL,
    [CARCODE] varchar(4) NULL,
    [DEL_INS1] varchar(40) NULL,
    [DEL_INS2] varchar(100) NULL,
    [SPL_INS] varchar(100) NULL,
    [ORDSTATUS] char(1) NULL,
    [AMDORDNO] varchar(15) NULL,
    [AMDORDDT] datetime NULL,
    [REFORDNO] varchar(15) NULL,
    [REFORDDT] datetime NULL,
    [CANFLG] char(1) NULL,
    [CANDT] datetime NULL,
    [CRDDAYS] numeric(3,0) NULL,
    [REMINDER] varchar(30) NULL,
    [REASON] varchar(80) NULL,
    [REMARKS] varchar(60) NULL,
    [SAMPLED] char(1) NULL,
    [OCTROIPER] numeric(5,2) NULL,
    [APPBY] varchar(25) NULL,
    [APPROVED] char(1) NULL,
    [INSPECT] char(1) NULL,
    [FILENO] varchar(15) NULL,
    [DELTXT] varchar(15) NULL,
    [BLCODE] varchar(2) NULL,
    [GLCODE] varchar(10) NULL,
    [GLHEAD] varchar(20) NULL,
    [discount] varchar(28) NULL,
    [tax] varchar(28) NULL,
    [BEd] varchar(28) NULL,
    [pack] varchar(28) NULL,
    [refno] varchar(100) NULL,
    [attn] varchar(100) NULL,
    [pack_charge] varchar(1) NULL,
    [EDUCESSPER] numeric(5,2) NULL,
    [EDUCESSAMT] numeric(15,2) NULL,
    [roff] numeric(5,2) NULL,
    [PACK_FLG] varchar(1) NULL,
    [FRT_FLG] varchar(1) NULL,
    [EXC_FLG] varchar(1) NULL,
    [Ins_Flg] varchar(1) NULL,
    [TAX_CODE] varchar(3) NULL,
    [duedate] datetime NULL,
    [chqno] varchar(20) NULL,
    [chqdt] datetime NULL,
    [Cess_Flg] varchar(1) NULL,
    [Cessper] numeric(5,2) NULL,
    [HsCessper] numeric(5,2) NULL,
    [DIRECT_INS] varchar(100) NULL,
    [PUTYPE] varchar(5) NULL,
    [CFORM] varchar(1) NULL,
    [FORMH] varchar(1) NULL,
    [FORM17] varchar(1) NULL,
    [CFORMREF] varchar(15) NULL,
    [FORMHREF] varchar(15) NULL,
    [FORM17REF] varchar(15) NULL,
    [disflg] char(1) NULL,
    [alert_raised] varchar(1) NULL,
    [FORM_TYPE] varchar(5) NULL,
    [CurrCode] varchar(3) NULL,
    [FCurRate] numeric(10,2) NULL,
    [Note] varchar(200) NULL,
    [conflg] char(1) NULL,
    [User_Id] varchar(5) NULL,
    [note2] varchar(200) NULL,
    [Billadd] varchar(10) NULL,
    [CancelCode] varchar(2) NULL,
    [ADDTAXPER] numeric(5,2) NULL,
    [ADDTAXAMT] numeric(15,2) NULL,
    [ADDTAX_CODE] varchar(5) NULL,
    [Ins_Amt] numeric(10,2) NULL,
    [Pack_Amt] numeric(10,2) NULL,
    [RefDate] datetime NULL,
    [PoIToAC] char(1) NULL,
    [FCloseddt] datetime NULL,
    [RemarksPF] varchar(30) NULL,
    [RemarksIns] varchar(30) NULL,
    [RemarksFrt] varchar(30) NULL,
    [PriceTerm] varchar(10) NULL,
    [FCACharg] numeric(9,2) NULL,
    [Pay_Code] varchar(5) NULL,
    [PrePrintFlg] varchar(1) NULL,
    [PrePrintUserID] varchar(10) NULL,
    [PrePrintDate] datetime NULL,
    [aPPPrintFlg] varchar(1) NULL,
    [aPPPrintUserID] varchar(10) NULL,
    [appPrintDate] datetime NULL,
    [Reminderflag] char(1) NULL,
    [Appip] varchar(25) NULL,
    [Appdate] datetime NULL,
    [Appuserid] varchar(10) NULL,
    [postponedt] datetime NULL,
    [closed_qty] varchar(20) NULL,
    [Io_qty] numeric(9,3) NULL,
    [FirstlevelApp] char(1) NULL,
    [FirstlevlAppDate] datetime NULL,
    [FirstlevlAppUserID] varchar(20) NULL,
    [Firstlevelpostponedt] datetime NULL,
    [CGSTAMT] numeric(15,2) NULL,
    [SGSTAMT] numeric(15,2) NULL,
    [IGSTAMT] numeric(15,2) NULL,
    [cust_gststcode] varchar(2) NULL,
    [cust_gstinno] varchar(15) NULL,
    [secondlevelappdate] datetime NULL,
    [thirdlevelappdate] datetime NULL,
    [rcm] char(1) NULL,
    [SecondLevelapp] varchar(5) NULL,
    [SecondLevelAppUserId] varchar(20) NULL,
    [SecondLevelPostPoneDt] datetime NULL,
    [createdby] varchar(50) NULL,
    [createddt] datetime NULL,
    [htcs_amt] numeric(15,2) NULL,
    [ThirdLevelAppUserId] varchar(20) NULL,
    [FourthLevelAppUserId] varchar(20) NULL,
    [FourthLevelAppDate] datetime NULL,
    [thirdlevelapp] varchar(10) NULL,
    [fourthlevelapp] varchar(10) NULL,
    [advpaymenttype] varchar(10) NULL,
    [Mailsendingflg] varchar(2) NULL,
    CONSTRAINT [PK_PO_ORDH] PRIMARY KEY ([DIVCODE], [PORDNO], [PORDDT], [POGRP])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_ORDL]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_ORDL]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [PORDNO] numeric(6,0) NOT NULL,
    [PORDDT] datetime NOT NULL,
    [POGRP] varchar(2) NOT NULL,
    [PORDSNO] numeric(5,0) NOT NULL,
    [PRNO] numeric(6,0) NULL,
    [PRDATE] datetime NULL,
    [PRSNO] numeric(5,0) NULL,
    [ITEMCODE] varchar(10) NULL,
    [RATE] decimal(15,4) NULL,
    [ORDQTY] numeric(12,3) NULL,
    [ORDVAL] numeric(15,2) NULL,
    [RCVDQTY] numeric(12,3) NULL,
    [CANQTY] numeric(12,3) NULL,
    [TAXPER] numeric(5,2) NULL,
    [TAXAMT] numeric(15,2) NULL,
    [EXDPER] numeric(5,2) NULL,
    [SEDPER] numeric(5,2) NULL,
    [SURPER] numeric(5,2) NULL,
    [DISPER] numeric(5,2) NULL,
    [DISAMT] numeric(15,2) NULL,
    [EXCAMT] numeric(15,2) NULL,
    [MODVAT] numeric(15,2) NULL,
    [STATUS] char(1) NULL,
    [PACKPER] numeric(5,2) NULL,
    [UNIT] varchar(3) NULL,
    [OTHCHGS] numeric(15,2) NULL,
    [REMARKS] varchar(200) NULL,
    [WEIGHT] numeric(12,3) NULL,
    [quotno] numeric(6,0) NULL,
    [quotdt] datetime NULL,
    [OCTROIPER] numeric(5,2) NULL,
    [EDINCL] numeric(9,2) NULL,
    [EDTYPE] char(1) NULL,
    [MAKPARTNO] varchar(20) NULL,
    [BLCODE] varchar(2) NULL,
    [CESS_PER] numeric(5,2) NULL,
    [CESS_AMT] numeric(15,2) NULL,
    [CCCODE] numeric(5,0) NULL,
    [PACKAMT] numeric(11,3) NULL,
    [SURAMT] numeric(11,2) NULL,
    [attn] varchar(50) NULL,
    [ITEMMEMO] varchar(500) NULL,
    [educessper] decimal(5,2) NULL,
    [AEDAMT] numeric(15,2) NULL,
    [TAX_CODE] varchar(5) NULL,
    [ADSC_PER] numeric(5,2) NULL,
    [ADSC_AMT] numeric(15,2) NULL,
    [INS_PER] numeric(5,2) NULL,
    [INS_AMT] numeric(15,2) NULL,
    [LANDCOST] numeric(15,2) NULL,
    [EDUCESSAMT] numeric(15,2) NULL,
    [FRGT1PER] numeric(5,2) NULL,
    [FRGT1AMT] numeric(15,2) NULL,
    [Hscess_per] numeric(5,2) NULL,
    [Hscess_Amt] numeric(15,2) NULL,
    [PACK_FLG] varchar(1) NULL,
    [FRT_FLG] varchar(1) NULL,
    [EXC_FLG] varchar(1) NULL,
    [Ins_Flg] varchar(1) NULL,
    [Cess_Flg] varchar(1) NULL,
    [DISFLG] varchar(1) NULL,
    [FRT2_PER] numeric(5,2) NULL,
    [FRT2_AMT] numeric(15,2) NULL,
    [PACK2_PER] numeric(5,2) NULL,
    [PACK2_AMT] numeric(15,2) NULL,
    [INS2_PER] numeric(5,2) NULL,
    [INS2_AMT] numeric(15,2) NULL,
    [roff] numeric(5,2) NULL,
    [vcat] varchar(2) NULL,
    [DepCode] varchar(3) NULL,
    [FRate] numeric(15,2) NULL,
    [FValue] numeric(15,2) NULL,
    [ADDTAXPER] numeric(5,2) NULL,
    [ADDTAXAMT] numeric(15,2) NULL,
    [ADDTAX_CODE] varchar(5) NULL,
    [SubCost] numeric(5,0) NULL,
    [AO_AppFlg] char(1) NULL,
    [EO_AppFlg] char(1) NULL,
    [VAT_Claim] char(1) NULL,
    [Excise_claim] char(1) NULL,
    [LCANFLG] char(1) NULL,
    [LCancelCode] varchar(4) NULL,
    [LCANDT] datetime NULL,
    [FCloseddt] datetime NULL,
    [AmedReason] varchar(30) NULL,
    [Pay_GuaranteeRmk] varchar(200) NULL,
    [FCACharg] numeric(9,2) NULL,
    [onlineremarks] varchar(20) NULL,
    [Closed_Qty] numeric(15,3) NULL,
    [Io_qty] numeric(9,2) NULL,
    [Fclosed] char(1) NULL,
    [cgstper] numeric(5,2) NULL,
    [cgstamt] numeric(10,2) NULL,
    [sgstper] numeric(5,2) NULL,
    [sgstamt] numeric(10,2) NULL,
    [igstper] numeric(5,2) NULL,
    [igstamt] numeric(10,2) NULL,
    [hsncode] varchar(8) NULL,
    [cgst_tax_code] varchar(5) NULL,
    [sgst_tax_code] varchar(5) NULL,
    [igst_tax_code] varchar(5) NULL,
    [deletereason] varchar(25) NULL,
    [tcs_per] decimal(15,4) NULL,
    [tcs_amt] decimal(15,2) NULL,
    CONSTRAINT [PK_PO_ORDL] PRIMARY KEY ([DIVCODE], [PORDNO], [PORDDT], [POGRP], [PORDSNO])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_PARA]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_PARA]
    (
    [STSUPL] varchar(2) NULL,
    [POFORMNO] varchar(10) NULL,
    [AppUserLevel2] numeric(5,0) NULL,
    [AppUserLevel3] numeric(5,0) NULL,
    [AppUserLabel1] varchar(35) NULL,
    [AppUserLabel2] varchar(35) NULL,
    [AppUserLabel3] varchar(35) NULL,
    [Adv_PayType] varchar(1) NULL,
    [divcode] varchar(2) NULL,
    [APPUSERLEVEL1] numeric(5,0) NULL,
    [RoundOff] numeric(5,2) NULL,
    [BudGrp] char(1) NULL,
    [CurrCode] varchar(3) NULL,
    [ManIndNo] char(1) NULL,
    [Po_Confirm] char(1) NULL,
    [Manual_IndNo] char(1) NULL,
    [PoAppUserLevel1] numeric(5,0) NULL,
    [PoAppUserLevel2] numeric(5,0) NULL,
    [PoAppUserLabel1] varchar(35) NULL,
    [PoAppUserLabel2] varchar(35) NULL,
    [PoAppAmount] numeric(5,2) NULL,
    [Delivery] numeric(5,0) NULL,
    [Quality] numeric(5,0) NULL,
    [penalty] numeric(5,0) NULL,
    [Pr_ILevel] char(1) NULL,
    [Pr_FLevel] char(1) NULL,
    [AmdafterGRN] char(1) NULL,
    [BudgetQty] char(1) NULL,
    [Supp_Item_Tax_Link] char(1) NULL,
    [EO_USERID] varchar(5) NULL,
    [AO_USERID] varchar(5) NULL,
    [PoRatePer] numeric(5,2) NULL,
    [PoQtyPer] numeric(5,2) NULL,
    [Rodepcode] varchar(3) NULL,
    [InditemGrp] char(1) NULL,
    [BudgetControl] char(1) NULL,
    [AutoMailCC] varchar(50) NULL,
    [AutoMailflg] char(1) NULL,
    [GRNAutoSMSflg] char(1) NULL,
    [EmpMasterComm] char(1) NULL,
    [PRSMSSendFlg] char(1) NULL,
    [PRSMSStatusFlg] char(1) NULL,
    [POSMSSendFlg] char(1) NULL,
    [POSMSStatusFlg] char(1) NULL,
    [PRSMSCatCode] numeric(5,0) NULL,
    [POSMSCatCode] numeric(5,0) NULL,
    [PoFirstLevelApp] char(1) NULL,
    [pomannual] varchar(1) NULL,
    [PORATEVALIDATION] char(1) NULL,
    [pofinalApplimit] decimal(18,2) NULL,
    [pofinalAppflg] char(1) NULL,
    [purtypeflg] varchar(5) NULL,
    [pendingorderpara] varchar(5) NULL,
    [finalapprovalpending] varchar(5) NULL,
    [webreportlink] varchar(100) NULL,
    [PDFExportFlag] char(1) NULL,
    [PoFinallevelApp] varchar(10) NULL,
    [pendrfq] varchar(10) NULL,
    [Penpodetails] varchar(10) NULL,
    [poprintapp] char(2) NULL,
    [PRapprovalstatus] varchar(5) NULL,
    [POapprovalstatus] varchar(5) NULL,
    [SPOapprovalstatus] varchar(5) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_PRH]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_PRH]
    (
    [divcode] varchar(2) NOT NULL,
    [prno] numeric(6,0) NOT NULL,
    [prdate] datetime NOT NULL,
    [depcode] varchar(3) NULL,
    [refno] varchar(20) NULL,
    [planno] numeric(6,0) NULL,
    [plandt] datetime NULL,
    [APPFLG] char(1) NULL,
    [ITYPE] char(1) NULL,
    [SECTION] varchar(20) NULL,
    [PLACEOFISS] varchar(30) NULL,
    [APP2] varchar(10) NULL,
    [APP3] varchar(10) NULL,
    [APP1DATE] datetime NULL,
    [APP2DATE] datetime NULL,
    [APP3DATE] datetime NULL,
    [APP1TIME] datetime NULL,
    [APP2TIME] datetime NULL,
    [APP3TIME] datetime NULL,
    [APP1] varchar(10) NULL,
    [REQNAME] varchar(10) NULL,
    [cancelflag] char(1) NULL,
    [canceldt] datetime NULL,
    [canreason] varchar(250) NULL,
    [amendno] numeric(5,0) NULL,
    [scopecode] varchar(2) NULL,
    [alert_raised] varchar(1) NULL,
    [userId] varchar(50) NULL,
    [SubCost] numeric(5,0) NULL,
    [budgetBALAMT] numeric(18,2) NULL,
    [PO_GRP] varchar(5) NULL,
    [saleorderno] varchar(25) NULL,
    [Saleorderdt] datetime NULL,
    [saletype] varchar(5) NULL,
    [thirlevelapp] varchar(10) NULL,
    [createdby] varchar(50) NULL,
    [createddt] varchar(25) NULL,
    CONSTRAINT [PK_PO_PRH] PRIMARY KEY ([divcode], [prno], [prdate])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_PRL]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_PRL]
    (
    [divcode] varchar(2) NOT NULL,
    [prno] numeric(6,0) NOT NULL,
    [prdate] datetime NOT NULL,
    [prsno] numeric(5,0) NOT NULL,
    [itemcode] varchar(10) NOT NULL,
    [macno] varchar(5) NULL,
    [qtyind] numeric(12,3) NULL,
    [qtyreqd] numeric(12,3) NULL,
    [qtyord] numeric(12,3) NULL,
    [qtyrec] numeric(12,3) NULL,
    [reqddate] datetime NULL,
    [prstatus] char(1) NULL,
    [remarks] varchar(50) NULL,
    [pend_flag] char(1) NULL,
    [slcode] varchar(6) NULL,
    [CCCODE] numeric(4,0) NULL,
    [CATCODE] varchar(1) NULL,
    [REMARK1] varchar(25) NULL,
    [RATE] numeric(13,4) NULL,
    [VALUE] numeric(13,2) NULL,
    [pino] decimal(6,0) NULL,
    [pidate] datetime NULL,
    [MAKPARTNO] varchar(20) NULL,
    [PLACE] varchar(40) NULL,
    [APPCOST] numeric(11,2) NULL,
    [BGRPCODE] varchar(4) NULL,
    [BLCODE] varchar(5) NULL,
    [ITEMMEMO] varchar(200) NULL,
    [Enq_Qty] numeric(15,3) NULL,
    [AUPFLAG] varchar(1) NULL,
    [curstock] numeric(12,3) NULL,
    [LPO_RATE] numeric(13,4) NULL,
    [LPO_DATE] datetime NULL,
    [PUR_FROM] varchar(8) NULL,
    [AmdFlg] char(1) NULL,
    [DirectApp] char(1) NULL,
    [DirectAppDate] datetime NULL,
    [Depcode] varchar(3) NULL,
    [FirstApp] char(1) NULL,
    [SecondApp] char(1) NULL,
    [ThirdApp] char(1) NULL,
    [FirstAppQty] numeric(12,3) NULL,
    [SecondAppQty] numeric(12,3) NULL,
    [ThirdAppQty] numeric(12,3) NULL,
    [AppQty1] numeric(12,3) NULL,
    [AppQty2] numeric(12,3) NULL,
    [AppQty3] numeric(12,3) NULL,
    [AppQty4] numeric(12,3) NULL,
    [FirstappUser] varchar(35) NULL,
    [SecondAppUser] varchar(35) NULL,
    [ThirdAppUser] varchar(35) NULL,
    [FinalAppUser] varchar(35) NULL,
    [FinalLevel_Remarks] varchar(20) NULL,
    [FinalAppQty] numeric(12,3) NULL,
    [Sample] char(1) NULL,
    [SubCost] numeric(5,0) NULL,
    [FClosed] char(1) NULL,
    [FCloseddt] datetime NULL,
    [BeforeFinalLevelApp] char(1) NULL,
    [BeforeFinalLevelAppDate] datetime NULL,
    [BeforeFinalLevelAppUserID] varchar(20) NULL,
    [deletereason] varchar(100) NULL,
    CONSTRAINT [PK_PO_PRL] PRIMARY KEY ([divcode], [prno], [prdate], [prsno])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[po_txndelreason]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[po_txndelreason]
    (
    [Delcode] varchar(15) NULL,
    [Delreason] varchar(150) NULL,
    [active] varchar(5) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PO_TYPE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PO_TYPE]
    (
    [TYPE_CODE] varchar(2) NOT NULL,
    [TYPNAME] varchar(40) NOT NULL,
    [CapGoodsFlg] varchar(1) NULL,
    [active] varchar(5) NULL,
    CONSTRAINT [PK_PO_TYPE] PRIMARY KEY ([TYPE_CODE])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PP_DIVMAS]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PP_DIVMAS]
    (
    [DIVCODE] varchar(2) NOT NULL,
    [DIVNAME] varchar(50) NOT NULL,
    [ABBR] varchar(25) NULL,
    [ADD1] varchar(60) NULL,
    [ADD2] varchar(60) NULL,
    [ADD3] varchar(60) NULL,
    [CITY] varchar(25) NULL,
    [PINCODE] varchar(15) NULL,
    [ZIP] varchar(10) NULL,
    [PHONE1] varchar(30) NULL,
    [PHONE2] varchar(30) NULL,
    [PHONE3] varchar(30) NULL,
    [GRAMS] varchar(15) NULL,
    [TELEX] varchar(15) NULL,
    [FAX] varchar(20) NULL,
    [EMAIL] varchar(40) NULL,
    [WEBADDR] varchar(35) NULL,
    [STARTMONTH] decimal(2,0) NULL,
    [VATNO] varchar(15) NULL,
    [VATDT] datetime NULL,
    [TNGST] varchar(30) NULL,
    [TNGSTDT] datetime NULL,
    [CGSTDT] datetime NULL,
    [CGST] varchar(30) NULL,
    [EXCODE] varchar(25) NULL,
    [compcode] varchar(2) NOT NULL,
    [divtype] char(1) NOT NULL,
    [SERVER_ALIAS] varchar(30) NULL,
    [DATABASE_NAME] varchar(30) NULL,
    [DB_USERID] varchar(30) NULL,
    [DB_PASSWORD] varchar(30) NULL,
    [RC_NO] varchar(25) NULL,
    [RANGE] varchar(50) NULL,
    [RANGE_ADDR1] varchar(50) NULL,
    [RANGE_ADDR2] varchar(50) NULL,
    [RANGE_ADDR3] varchar(50) NULL,
    [DIVISION] varchar(50) NULL,
    [DIVISION_ADDR1] varchar(50) NULL,
    [DIVISION_ADDR2] varchar(50) NULL,
    [DIVISION_ADDR3] varchar(50) NULL,
    [COLLECTORATE] varchar(25) NULL,
    [CE_CODE] varchar(25) NULL,
    [MFG_CODE] varchar(25) NULL,
    [MFGRS_CODE] varchar(25) NULL,
    [WAREHOUSE] varchar(50) NULL,
    [STATE_CODE] varchar(10) NULL,
    [IE_CODE] varchar(25) NULL,
    [RBI_CODE] varchar(25) NULL,
    [BRANCH_AREA] varchar(50) NULL,
    [SPINDLES] numeric(8,0) NULL,
    [RANGE_CODE] varchar(15) NULL,
    [DIVISION_CODE] varchar(15) NULL,
    [COMM_CODE] varchar(15) NULL,
    [BANK_CODE] varchar(15) NULL,
    [STATENAME] varchar(25) NULL,
    [PAN] varchar(20) NULL,
    [TINNO] varchar(20) NULL,
    [ecc] varchar(20) NULL,
    [hpincode] varchar(15) NULL,
    [hcity] varchar(15) NULL,
    [pt_store] varchar(2) NULL,
    [pt_broker] varchar(2) NULL,
    [pt_lsales] varchar(2) NULL,
    [pt_export] varchar(2) NULL,
    [pt_cotton] varchar(2) NULL,
    [UNIT_NAME] varchar(20) NULL,
    [CUST_ID] varchar(10) NULL,
    [HODivname] varchar(60) NULL,
    [HOADD1] varchar(60) NULL,
    [HOADD2] varchar(60) NULL,
    [HOADD3] varchar(60) NULL,
    [HOCity] varchar(60) NULL,
    [HOState] varchar(60) NULL,
    [HOCountry] varchar(60) NULL,
    [HOPin] varchar(15) NULL,
    [HOFax] varchar(20) NULL,
    [HOEmail] varchar(40) NULL,
    [HOPhone] varchar(30) NULL,
    [SUB_TITLE] varchar(50) NULL,
    [DIV_PRINTNAME] varchar(40) NULL,
    [DIV_UNITNAME] varchar(30) NULL,
    [TAN] varchar(10) NULL,
    [tdsSTdCode] varchar(5) NULL,
    [tdsPhoneNo] varchar(10) NULL,
    [YarnInvPrefix] varchar(5) NULL,
    [CXSNo] varchar(25) NULL,
    [CE_ABBR] varchar(20) NULL,
    [CE_DivName] varchar(100) NULL,
    [MRS_ITEM_SELECTION] varchar(5) NULL,
    [LokupTimerEnable] char(1) NULL,
    [DIV_LOGO] image NULL,
    [HOEmail2] varchar(20) NULL,
    [LIC_DIVNAME] varchar(2000) NULL,
    [LIC_Version] varchar(1000) NULL,
    [DM_Date] datetime NULL,
    [Pur_email] varchar(40) NULL,
    [MARK_MAIL] varchar(40) NULL,
    [Div_Prefix] varchar(10) NULL,
    [Location_Code] varchar(10) NULL,
    [hocellno] varchar(15) NULL,
    [ISO_Logo] image NULL,
    [CE_CITY] varchar(50) NULL,
    [AutoMailFromID] varchar(40) NULL,
    [AutoMailFromIDPwd] varchar(20) NULL,
    [smtpserver] varchar(100) NULL,
    [smtpport] numeric(5,0) NULL,
    [mark_mailpwd] varchar(50) NULL,
    [pur_emailpasswd] varchar(50) NULL,
    [country] varchar(50) NULL,
    [cinno] varchar(30) NULL,
    [SCRRES_CHANGE] char(1) NULL,
    [CUST_ID1] varchar(6) NULL,
    [RTGSDivname] varchar(100) NULL,
    [gststatecode] varchar(2) NULL,
    [gstinno] varchar(15) NULL,
    [bank_code1] varchar(15) NULL,
    [exportref] varchar(12) NULL,
    [CIN_NO] varchar(25) NULL,
    [RMPur_Email] varchar(20) NULL,
    [EinvoiceFlg] char(1) NULL,
    [Einvoice_flg] char(1) NULL,
    [EMAIL1] varchar(100) NULL,
    [EInvPrefix] char(2) NULL,
    [password_policy_flag] varchar(10) NULL,
    [yarnmailid] varchar(25) NULL,
    [GroupMillID] varchar(5) NULL,
    CONSTRAINT [PK_PP_DIVMAS] PRIMARY KEY ([DIVCODE])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PP_PASSWD]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PP_PASSWD]
    (
    [divcode] varchar(2) NOT NULL,
    [user_id] varchar(5) NOT NULL,
    [alevel] decimal(3,0) NOT NULL,
    [password] varchar(10) NULL,
    [user_name] varchar(35) NULL,
    [module] numeric(2,0) NOT NULL,
    [PENTRY_LOCK] char(1) NULL,
    [LOCK_DAYS] numeric(3,0) NULL,
    [idleminutes] numeric(9,0) NULL,
    [idletimeflg] numeric(9,0) NULL,
    [idletimerflg] numeric(9,0) NULL,
    [activeflg] char(1) NULL,
    CONSTRAINT [PK_PP_PASSWD] PRIMARY KEY ([divcode], [user_id], [alevel], [module])
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PR_DESIG]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PR_DESIG]
    (
    [desigcode] varchar(3) NOT NULL,
    [desigdesc] varchar(30) NOT NULL,
    [divcode] varchar(2) NULL,
    [Grade] varchar(2) NULL,
    [GDesc] varchar(30) NULL
    );
END;
GO

IF OBJECT_ID(N'[dbo].[PR_EMP]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PR_EMP]
    (
    [divcode] varchar(2) NOT NULL,
    [empno] decimal(5,0) NOT NULL,
    [wcat] varchar(2) NULL,
    [depcode] varchar(3) NULL,
    [ename] varchar(30) NOT NULL,
    [fhname] varchar(30) NULL,
    [ticketno] varchar(15) NULL,
    [dob] datetime NULL,
    [doj] datetime NULL,
    [dor] datetime NULL,
    [sex] char(1) NULL,
    [shift] char(1) NULL,
    [pfflg] char(1) NULL,
    [pfno] varchar(20) NULL,
    [pfrate] decimal(6,4) NULL,
    [erpfrate] decimal(6,4) NULL,
    [esiflg] char(1) NULL,
    [esino] varchar(15) NULL,
    [esiloc] varchar(30) NULL,
    [bonelig] char(1) NULL,
    [bankaccno] varchar(20) NULL,
    [weekoff] decimal(1,0) NULL,
    [fpfno] decimal(6,0) NULL,
    [unionflg] char(1) NULL,
    [desigcode] varchar(3) NULL,
    [paymode] decimal(1,0) NULL,
    [loc_os] char(1) NULL,
    [citycode] decimal(4,0) NULL,
    [grpcode] varchar(2) NULL,
    [DAELIG] char(1) NULL,
    [PRV_DAYS] decimal(4,2) NULL,
    [UNIONCODE] varchar(3) NULL,
    [NFHELIG] char(1) NULL,
    [RATEFLG] char(1) NULL,
    [SHIFT_0] bit NULL,
    [SHIFT_1] bit NULL,
    [SHIFT_2] bit NULL,
    [SHIFT_3] bit NULL,
    [BLOOD_GROUP] varchar(2) NULL,
    [EMP_IMAGE] image NULL,
    [ADD1] varchar(50) NULL,
    [ADD2] varchar(50) NULL,
    [ADD3] varchar(50) NULL,
    [VCODE] varchar(3) NULL,
    [PHONE] varchar(20) NULL,
    [QUALI] varchar(20) NULL,
    [ELEFT] varchar(1) NULL,
    [EMPRCODE] varchar(10) NULL,
    [CCODE] varchar(3) NULL,
    [RFLEFT] varchar(50) NULL,
    [PFDATE] datetime NULL,
    [WKCAT] varchar(2) NULL,
    [sta_shift] char(2) NULL,
    [nodays] numeric(5,0) NULL,
    [schemedate] datetime NULL,
    [INCENFLG] char(1) NULL,
    [empimage] image NULL,
    [BrName] varchar(30) NULL,
    [imagepath] varchar(90) NULL,
    [schcode] varchar(2) NULL,
    [AGEFLG] varchar(1) NULL,
    [DOCFLG] varchar(1) NULL,
    [phone1] varchar(20) NULL,
    [CITY] varchar(30) NULL,
    [PINCODE] numeric(10,0) NULL,
    [schamt] numeric(18,2) NULL,
    [hostelflag] varchar(1) NULL,
    [tc] char(1) NULL,
    [Rcard] char(1) NULL,
    [shiftchangeday] decimal(18,0) NULL,
    [Pensionflg] char(1) NULL,
    [HOSTEL_ELIG] char(1) NULL,
    [ProdBasedSalary] char(1) NULL,
    [PFEffDate] datetime NULL,
    [ESIEffDate] datetime NULL,
    [Shift_Batch] char(1) NULL,
    [monthlyshiftchange] varchar(2) NULL,
    [RejoinDt] datetime NULL,
    [PAN] varchar(10) NULL,
    [RefEmpNo] decimal(5,0) NULL,
    [RefOther] varchar(20) NULL,
    [TAdd1] varchar(100) NULL,
    [TAdd2] varchar(100) NULL,
    [TAdd3] varchar(100) NULL,
    [TVcode] varchar(3) NULL,
    [TPinCode] numeric(10,0) NULL,
    [ContPerName] varchar(25) NULL,
    [ContPerPh] varchar(15) NULL,
    [TCity] varchar(20) NULL,
    [Active] char(1) NULL,
    [OwnVehicle] char(1) NULL,
    [VisibleId1] varchar(50) NULL,
    [VisibleId2] varchar(50) NULL,
    [HOBBIES] varchar(50) NULL,
    [RelCd] varchar(2) NULL,
    [ComCd] varchar(2) NULL,
    [PostApplied] varchar(30) NULL,
    [MarUnMar] char(1) NULL,
    [DateofMar] datetime NULL,
    [OwnRentHouse] char(1) NULL,
    [MonthlyRent] decimal(10,0) NULL,
    [MonthlyIncome] decimal(10,0) NULL,
    [VehicleNo] varchar(15) NULL,
    [Licence] char(1) NULL,
    [Height] decimal(6,2) NULL,
    [Weight] decimal(6,2) NULL,
    [QualiCode] varchar(2) NULL,
    [EsiCode] varchar(2) NULL,
    [Cityname] varchar(1) NULL,
    [Gcode] varchar(2) NULL,
    [Unitcode] varchar(2) NULL,
    [InsuranceFlg] char(1) NULL,
    [StoreSubsidyFlg] char(1) NULL,
    [Insfperiod] varchar(6) NULL,
    [Instperiod] varchar(6) NULL,
    [InsPreMonth] datetime NULL,
    [EContriEligible] char(1) NULL,
    [BLCODE] varchar(3) NULL,
    [EmailID] varchar(30) NULL,
    [BANK_CODE] varchar(5) NULL,
    [AgeProof_flg] char(1) NULL,
    [AP_CertNo] varchar(20) NULL,
    [AP_CertDT] datetime NULL,
    [AP_CertTokenRef] varchar(20) NULL,
    [Permanent_flg] char(1) NULL,
    [Permanent_Dt] datetime NULL,
    [Service480days_flg] char(1) NULL,
    [Service480days_Dt] datetime NULL,
    [SeronSimilarWork] numeric(5,0) NULL,
    [JOBCODE] varchar(2) NULL,
    [SCODE] varchar(2) NULL,
    [EXPERIENCE] decimal(18,0) NULL,
    [STATION] char(1) NULL,
    [PER_ADD1] varchar(100) NULL,
    [PER_ADD2] varchar(100) NULL,
    [PER_ADD3] varchar(100) NULL,
    [CON_ADD1] varchar(100) NULL,
    [CON_ADD2] varchar(100) NULL,
    [CON_ADD3] varchar(100) NULL,
    [MOTRAN] char(1) NULL,
    [BSAL] decimal(18,0) NULL,
    [Mac_Ticketno] varchar(10) NULL,
    [HostalFlg] char(1) NULL,
    [PLCLFLg] char(1) NULL,
    [vpf_flg] char(1) NULL,
    [CCCODE] varchar(5) NULL
    );
END;
GO

-- Foreign keys

-- Skipped [FK_FA_SLMAS_fa_prty] because parent table [fa_prty] is not present in tables.csv
-- ALTER TABLE [dbo].[FA_SLMAS] ADD CONSTRAINT [FK_FA_SLMAS_fa_prty] FOREIGN KEY ([prtytyp]) REFERENCES [dbo].[fa_prty] ([prtytyp]);
GO

-- Skipped [FK_FA_SLMAS_GROUP] because parent table [FA_GROUP] is not present in tables.csv
-- ALTER TABLE [dbo].[FA_SLMAS] ADD CONSTRAINT [FK_FA_SLMAS_GROUP] FOREIGN KEY ([GROUPCODE]) REFERENCES [dbo].[FA_GROUP] ([CODE]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IN_ITEM_IN_CAT')
BEGIN
    ALTER TABLE [dbo].[IN_ITEM] ADD CONSTRAINT [FK_IN_ITEM_IN_CAT] FOREIGN KEY ([CATCODE]) REFERENCES [dbo].[IN_CAT] ([CATCODE]);
END;
GO

-- Skipped [FK_IN_TRNHEAD_IN_TC] because parent table [IN_TC] is not present in tables.csv
-- ALTER TABLE [dbo].[IN_TRNHEAD] ADD CONSTRAINT [FK_IN_TRNHEAD_IN_TC] FOREIGN KEY ([TC]) REFERENCES [dbo].[IN_TC] ([TC]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IN_TRNTAIL_IN_ITEM')
BEGIN
    ALTER TABLE [dbo].[IN_TRNTAIL] ADD CONSTRAINT [FK_IN_TRNTAIL_IN_ITEM] FOREIGN KEY ([ITEMCODE]) REFERENCES [dbo].[IN_ITEM] ([ITEMCODE]);
END;
GO

-- Skipped [FK_PO_ENQL_PO_ENQH] because parent table [PO_ENQH] is not present in tables.csv
-- ALTER TABLE [dbo].[PO_ENQL] ADD CONSTRAINT [FK_PO_ENQL_PO_ENQH] FOREIGN KEY ([divcode], [enqno], [enqdt]) REFERENCES [dbo].[PO_ENQH] ([divcode], [enqno], [enqdt]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PO_ORDH_PO_TYPE')
BEGIN
    ALTER TABLE [dbo].[PO_ORDH] ADD CONSTRAINT [FK_PO_ORDH_PO_TYPE] FOREIGN KEY ([POGRP]) REFERENCES [dbo].[PO_TYPE] ([TYPE_CODE]);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PO_ORDL_PO_ORDH')
BEGIN
    ALTER TABLE [dbo].[PO_ORDL] ADD CONSTRAINT [FK_PO_ORDL_PO_ORDH] FOREIGN KEY ([DIVCODE], [PORDNO], [PORDDT], [POGRP]) REFERENCES [dbo].[PO_ORDH] ([DIVCODE], [PORDNO], [PORDDT], [POGRP]);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PO_ORDL_IN_ITEM')
BEGIN
    ALTER TABLE [dbo].[PO_ORDL] ADD CONSTRAINT [FK_PO_ORDL_IN_ITEM] FOREIGN KEY ([ITEMCODE]) REFERENCES [dbo].[IN_ITEM] ([ITEMCODE]);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PO_PRL_PO_PRH')
BEGIN
    ALTER TABLE [dbo].[PO_PRL] ADD CONSTRAINT [FK_PO_PRL_PO_PRH] FOREIGN KEY ([divcode], [prno], [prdate]) REFERENCES [dbo].[PO_PRH] ([divcode], [prno], [prdate]);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PO_PRL_IN_ITEM')
BEGIN
    ALTER TABLE [dbo].[PO_PRL] ADD CONSTRAINT [FK_PO_PRL_IN_ITEM] FOREIGN KEY ([itemcode]) REFERENCES [dbo].[IN_ITEM] ([ITEMCODE]);
END;
GO


