CREATE OR ALTER PROCEDURE dbo.ksp_RMI_PO_InsertLine
    @ContNo          VARCHAR(10),
    @ContDt          DATETIME,
    @DivCode         VARCHAR(2),
    @SupCd           VARCHAR(10)   = NULL,
    @BrkCd           VARCHAR(10)   = NULL,
    @AreaCode        VARCHAR(4)    = NULL,
    @VarCode         VARCHAR(10),
    @CntCode         VARCHAR(5)    = NULL,
    @BBFlag          CHAR(1)       = 'B',
    @OrdQty          DECIMAL(10,2) = 0,
    @OrdKgs          NUMERIC(18,3) = 0,
    @CandyRate       DECIMAL(9,4)  = 0,
    @RateKg          DECIMAL(9,4)  = 0,
    @PayMode         CHAR(2),
    @DlyType         CHAR(1),
    @ImInd           CHAR(1)       = 'L',
    @ArrivalType     VARCHAR(1)    = 'P',
    @DueDate         DATETIME      = NULL,
    @CropYear        VARCHAR(20)   = NULL,
    @Acceptance      VARCHAR(30)   = NULL,
    @PtyContNo       VARCHAR(20)   = NULL,
    @PlotNo          VARCHAR(10)   = NULL,
    @WosamplePrNo    VARCHAR(10)   = NULL,
    @PressMarkNo     VARCHAR(15)   = NULL,
    @RateUnit        VARCHAR(20)   = NULL,
    @Remarks         NVARCHAR(255) = NULL,
    @DeliveryAddCode VARCHAR(10)   = NULL,
    @BillingAddCode  VARCHAR(10)   = NULL,
    @ContactPerson   VARCHAR(50)   = NULL,
    @Season          VARCHAR(25)   = NULL,
    @MillRefNo       VARCHAR(20)   = NULL,
    @CashDisPer      NUMERIC(5,2)  = 0,
    @TradeDisPer     NUMERIC(5,2)  = 0,
    @CessPer         NUMERIC(5,2)  = 0,
    @InsPer          NUMERIC(6,3)  = 0,
    @TaxCode         VARCHAR(3)    = NULL,
    @TaxChoice       VARCHAR(10)   = 'SINGLE',
    @CreditDays      NUMERIC(9,2)  = 0,
    @InterestPer     NUMERIC(9,2)  = 0,
    @LotFrom         NUMERIC(12,0) = 0,
    @LotTo           NUMERIC(12,0) = 0,
    @FinalWeighment  VARCHAR(1)    = 'S',
    @SampleFlg       VARCHAR(1)    = 'N',
    @CommPer         NUMERIC(5,2)  = 0,
    @Terms1          VARCHAR(50)   = NULL,
    @Terms1Days      NUMERIC(5,0)  = 0,
    @Terms2          VARCHAR(50)   = NULL,
    @Terms2Days      NUMERIC(5,0)  = 0,
    @Transport       VARCHAR(50)   = NULL,
    @IPrNo           NUMERIC(5,0)  = NULL,
    @IPrDate         DATETIME      = NULL,
    @IPrSNo          NUMERIC(5,0)  = NULL,
    @CurrCode        VARCHAR(3)    = NULL,
    @DeliveryTerms   VARCHAR(200)  = NULL,
    @HSN             VARCHAR(8)    = NULL,
    @CgstPer         NUMERIC(5,2)  = 0,
    @SgstPer         NUMERIC(5,2)  = 0,
    @IgstPer         NUMERIC(10,2) = 0,
    @FTAmt           NUMERIC(6,2)  = 0,
    @FTFlg           VARCHAR(1)    = 'N',
    @PrepDate        DATETIME      = NULL,
    @SusCatType      VARCHAR(10)   = NULL,
    @PayCode         VARCHAR(5)    = NULL,
    @LineNo          VARCHAR(18)   = NULL,
    @PlCode          VARCHAR(5)    = NULL,
    @SupFileName     VARCHAR(80)   = NULL,
    @TcsPer          NUMERIC(9,3)  = 0,
    @Grade           VARCHAR(25)   = NULL,
    @Staple          VARCHAR(25)   = NULL,
    @Micronaire      VARCHAR(25)   = NULL,
    @Strength        VARCHAR(25)   = NULL,
    @Moisture        VARCHAR(25)   = NULL,
    @Trash           VARCHAR(25)   = NULL,
    @NoOfLoad        NUMERIC(2,0)  = 0,
    @MSDocNo         NUMERIC(8,0)  = NULL,
    @MSDocSno        NUMERIC(3,0)  = NULL,
    @FreightPerBale  NUMERIC(9,2)  = 0,
    @PreparedBy      VARCHAR(5)    = NULL,
    @Prefix          VARCHAR(2)    = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.RM_CONT
    (
        CONTNO, CONTDT, DIVCODE, SUPCD, BRKCD, AREACODE, VARCODE, CNTCODE,
        BBFLAG, ORDQTY, ORDKGS, CANDYRATE, RATEKG, PAYMODE, DLYTYPE, im_ind,
        arrivaltype, duedate, weignment, CROPYEAR, acceptance, PTY_CONTNO,
        PLOTNO, Prno, pressmarkno, rateunit, remarks, deladd, billadd,
        contperson, SEASON, MILLREFNO, CASHDISPER, TRADEDISPER, CESSPER,
        INSPER, TAX_CODE, TAX_CHOICE, CREDITDAYS, INTERESTPER,
        SUPPLIERLOTNOFROM, SUPPLIERLOTNOTO, FinalWeighment, SAMPLEFLG,
        CommPer, Terms1, Terms1Days, Terms2, Terms2Days, TransPort,
        IPRNO, PRDATE, PRSNO, CurrCode, DeliveryTerms, HSN,
        cgstper, sgstper, igstper, FTAmt, FTFlg, prepDate, SusCatType,
        paycode, Line_No, PlCode, SupFileName, TCS_PER, Grade, STAPLE,
        MIC, Strength, Moisture, Trash, No_of_Load, MSDocno, MSDocsno,
        freightperbale, Prepared_by, prefix, APPFLG, FIRST_APPFLG
    )
    VALUES
    (
        @ContNo, @ContDt, @DivCode, @SupCd, @BrkCd, @AreaCode, @VarCode, @CntCode,
        @BBFlag, @OrdQty, @OrdKgs, @CandyRate, @RateKg, @PayMode, @DlyType, @ImInd,
        @ArrivalType, @DueDate, '',  -- weignment always '' (CD-1 fix)
        @CropYear, @Acceptance, @PtyContNo,
        @PlotNo, @WosamplePrNo, @PressMarkNo, @RateUnit, @Remarks, @DeliveryAddCode, @BillingAddCode,
        @ContactPerson, @Season, @MillRefNo, @CashDisPer, @TradeDisPer, @CessPer,
        @InsPer, @TaxCode, @TaxChoice, @CreditDays, @InterestPer,
        @LotFrom, @LotTo, @FinalWeighment, @SampleFlg,
        @CommPer, @Terms1, @Terms1Days, @Terms2, @Terms2Days, @Transport,
        @IPrNo, @IPrDate, @IPrSNo, @CurrCode, @DeliveryTerms, @HSN,
        @CgstPer, @SgstPer, @IgstPer, @FTAmt, @FTFlg, ISNULL(@PrepDate, GETDATE()),
        @SusCatType, @PayCode, @LineNo, @PlCode, @SupFileName, @TcsPer,
        @Grade, @Staple, @Micronaire, @Strength, @Moisture, @Trash,
        @NoOfLoad, @MSDocNo, @MSDocSno, @FreightPerBale, @PreparedBy,
        @Prefix, 'N', 'N'
    );
END;
