CREATE OR ALTER PROCEDURE dbo.ksp_RMI_PO_UpdateLine
    @ContNo          VARCHAR(10),
    @ContDt          DATETIME,
    @DivCode         VARCHAR(2),
    @VarCode         VARCHAR(10),
    @OrdQty          DECIMAL(10,2) = 0,
    @OrdKgs          NUMERIC(18,3) = 0,
    @CandyRate       DECIMAL(9,4)  = 0,
    @RateKg          DECIMAL(9,4)  = 0,
    @BBFlag          CHAR(1)       = 'B',
    @DueDate         DATETIME      = NULL,
    @CropYear        VARCHAR(20)   = NULL,
    @Acceptance      VARCHAR(30)   = NULL,
    @Remarks         NVARCHAR(255) = NULL,
    @Season          VARCHAR(25)   = NULL,
    @MillRefNo       VARCHAR(20)   = NULL,
    @CashDisPer      NUMERIC(5,2)  = 0,
    @TradeDisPer     NUMERIC(5,2)  = 0,
    @CessPer         NUMERIC(5,2)  = 0,
    @InsPer          NUMERIC(6,3)  = 0,
    @TaxCode         VARCHAR(3)    = NULL,
    @TaxChoice       VARCHAR(10)   = 'SINGLE',
    @CreditDays      NUMERIC(9,2)  = 0,
    @InterestPer     NUMERIC(9,2)  = 0,
    @LotFrom         NUMERIC(12,0) = 0,
    @LotTo           NUMERIC(12,0) = 0,
    @CommPer         NUMERIC(5,2)  = 0,
    @Terms1          VARCHAR(50)   = NULL,
    @Terms1Days      NUMERIC(5,0)  = 0,
    @Terms2          VARCHAR(50)   = NULL,
    @Terms2Days      NUMERIC(5,0)  = 0,
    @Transport       VARCHAR(50)   = NULL,
    @CurrCode        VARCHAR(3)    = NULL,
    @DeliveryTerms   VARCHAR(200)  = NULL,
    @HSN             VARCHAR(8)    = NULL,
    @CgstPer         NUMERIC(5,2)  = 0,
    @SgstPer         NUMERIC(5,2)  = 0,
    @IgstPer         NUMERIC(10,2) = 0,
    @FTAmt           NUMERIC(6,2)  = 0,
    @FTFlg           VARCHAR(1)    = 'N',
    @SusCatType      VARCHAR(10)   = NULL,
    @PayCode         VARCHAR(5)    = NULL,
    @LineNo          VARCHAR(18)   = NULL,
    @PlCode          VARCHAR(5)    = NULL,
    @SupFileName     VARCHAR(80)   = NULL,
    @TcsPer          NUMERIC(9,3)  = 0,
    @Grade           VARCHAR(25)   = NULL,
    @Staple          VARCHAR(25)   = NULL,
    @Micronaire      VARCHAR(25)   = NULL,
    @Strength        VARCHAR(25)   = NULL,
    @Moisture        VARCHAR(25)   = NULL,
    @Trash           VARCHAR(25)   = NULL,
    @NoOfLoad        NUMERIC(2,0)  = 0,
    @FreightPerBale  NUMERIC(9,2)  = 0,
    @ModUserId       VARCHAR(5)    = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE dbo.RM_CONT
    SET
        ORDQTY         = @OrdQty,
        ORDKGS         = @OrdKgs,
        CANDYRATE      = @CandyRate,
        RATEKG         = @RateKg,
        BBFLAG         = @BBFlag,
        duedate        = @DueDate,
        CROPYEAR       = @CropYear,
        acceptance     = @Acceptance,
        remarks        = @Remarks,
        SEASON         = @Season,
        MILLREFNO      = @MillRefNo,
        CASHDISPER     = @CashDisPer,
        TRADEDISPER    = @TradeDisPer,
        CESSPER        = @CessPer,
        INSPER         = @InsPer,
        TAX_CODE       = @TaxCode,
        TAX_CHOICE     = @TaxChoice,
        CREDITDAYS     = @CreditDays,
        INTERESTPER    = @InterestPer,
        SUPPLIERLOTNOFROM = @LotFrom,
        SUPPLIERLOTNOTO   = @LotTo,
        CommPer        = @CommPer,
        Terms1         = @Terms1,
        Terms1Days     = @Terms1Days,
        Terms2         = @Terms2,
        Terms2Days     = @Terms2Days,
        TransPort      = @Transport,
        CurrCode       = @CurrCode,
        DeliveryTerms  = @DeliveryTerms,
        HSN            = @HSN,
        cgstper        = @CgstPer,
        sgstper        = @SgstPer,
        igstper        = @IgstPer,
        FTAmt          = @FTAmt,
        FTFlg          = @FTFlg,
        SusCatType     = @SusCatType,
        paycode        = @PayCode,
        Line_No        = @LineNo,
        PlCode         = @PlCode,
        SupFileName    = @SupFileName,
        TCS_PER        = @TcsPer,
        Grade          = @Grade,
        STAPLE         = @Staple,
        MIC            = @Micronaire,
        Strength       = @Strength,
        Moisture       = @Moisture,
        Trash          = @Trash,
        No_of_Load     = @NoOfLoad,
        freightperbale = @FreightPerBale,
        Mod_dt         = GETDATE(),
        Mod_UserId     = @ModUserId,
        Amdnos         = ISNULL(Amdnos, 0) + 1
    WHERE CONTNO  = @ContNo
      AND CONTDT  = @ContDt
      AND DIVCODE = @DivCode
      AND VARCODE = @VarCode;
END;
