global using Spinrise.Application.DTOs.Auth;
global using Spinrise.Application.DTOs.PurchaseRequisitions;
global using Spinrise.Application.Interfaces;
global using Spinrise.Application.Areas.Administration.Department.Interfaces;
global using Spinrise.Application.Areas.Common.Lookup.Interfaces;
global using Spinrise.Application.Areas.Common.Lookup.DTOs;
global using Spinrise.Application.Areas.Inventory.Stock.Interfaces;
global using Spinrise.Application.Areas.Inventory.Stock.DTOs;
global using Spinrise.Domain.Entities;
